# config.yml

twitter:
  api_key: "VOTRE_API_KEY"
  api_secret_key: "VOTRE_API_SECRET_KEY"
  access_token: "VOTRE_ACCESS_TOKEN"
  access_token_secret: "VOTRE_ACCESS_TOKEN_SECRET"
  bearer_token: 'VOTRE_BEARER_TOKEN'

mongodb:
  uri: "mongodb+srv://username:password@yourcluster.mongodb.net/test" 
  database_name: "social_media_db"
  collection_name: "posts"
